trigger:
  branches:
    include:
      - develop
    exclude:
      - feature/*
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-dependencies.yaml

  # Scripts for running all tests in a file and to run tests based on test case name (integration testing)
  - script: |
      robot --output results/logs/output_gui_test.xml --log results/logs/log_gui_test.html --report results/logs/report_gui_test.html tests/
    displayName: 'Run Test File "GUI"'

  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-develop'
    displayName: 'Publish Robot Framework Reports'


